name: Test

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        perl: [
          '5.10', '5.12', '5.14',
          '5.16', '5.20', '5.22',
          '5.24',
        ]
        threads: [ false, true ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.perl }}${{ matrix.threads && '-threads' || '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1
        with:
          multi-thread: ${{ matrix.threads }}
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - run: cpanm --installdeps --notest --skip-satisfied .
      - run: perl Makefile.PL
      - run: make test